default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: my_rails_app_development
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: 5432

test:
  <<: *default
  database: my_rails_app_test
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: 5432

production:
  <<: *default
  # url: <%= ENV['DATABASE_URL'] %>
  database: my_rails_app
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: 5432